### ISSUE TITLE
Xyloroll does not save status of keys

### ISSUE THREAD

**Issue by nikharron** [plaidpants/soundstagevr#30]
Not sure if this is a bug, or intended functionality.

When composing songs using the Xyloroll component, it's common to use the trigger to hold a set of notes to create arpeggios. The status of these keys is not saved, (or if it is, is not reestablished when loading a file). It limits the use of the app for composition.

P.S. Thank-you for the work in porting this! So far, it's hands down best VR experience I've had.

**Comment by plaidpants** [comment]
Should be resolved with the latest release
